language: node_js
node_js:
- '5'
notifications:
  email: false
  slack:
    secure: SJdDUXOFt1ruUueHhc1eAq8QveJPwCZojzblLIefCy7YB7TxB3av6wrGsveBoAN/rgWKwQMir8spZWss1+FtbYaMAMk2l4zlWQkKC79HA5oSRvEHyHw0/6eCOWfn5DBSnbHarhMfWgzQIBseEdT63kZCFJV02Ersu+OtTcowtq2WwZlhv48nCySvAey+l+EhwG/kQz8TDZw/ONRoFTu7yidRjlXAA3cqu2cPIm5c82IR3AlTSMeB84PYQhO8+kzhfHzEouP4wb7UqIr+p3un0ITVcTxnjwnjaXaW77Yh/8gOfLe5xECB0buibU9tZ9WqgaOSajfEzJJfcywdhRoREJURien9PA1lMntQA2Fslr+XzUL1t26apNX8aZg67vc3CHzTrGpMEhFSKORh0ihA/4Wlm7Jnj5Z7SdMRH8CihZAlI+O3/hAAuERKa5EOBrh6ynTNfoIjKX4aC47bBX78UuwZyiZSk3nmWHeE+422hohDfdQxEXTCOdts4i3McRytzy6ENdQoTkT/PO47SfyQUI3mWoC07whbPjlST38OdAZjtsxNDfQippCG+931Zipy1qLd0Kc2jCLeJ1ouIxCw4poU1PCezALbYEfZvSSY3LzYVfrjS6+1h4hKiF4YacGoMLmIkQNLSbaia1Z0q9NCYZ8oEbBa11cO7faaiHywBB0=
