version: '2.2'
services:
  choregg:
    image: danny624/choregg:latest
    container_name: choregg
    ports:
      - "3000:3000"
    environment:
      - mongoURI=mongodb://192.168.1.18:27017/choregg
      - NODE_ENV=production
    links:
      - choregg_db
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 192.168.1.18:3000 || exist 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    depends_on:
      choregg_db:
        condition: service_healthy
  choregg_db:
    image: mongo:latest
    container_name: choregg_db
    ports:
    - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 192.168.1.18:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ./mongo-volume:/data/db
